# Generated by Django 3.2.5 on 2021-07-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='ykl',
        ),
    ]
