# Generated by Django 3.2.5 on 2021-07-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoy', '0003_auto_20210727_2007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
